table Fuente
	lineageTag: c6e1b5cf-f124-48ca-a3ad-eb0ec82746b7

	column id_fuente
		dataType: int64
		formatString: 0
		lineageTag: 54e0c326-fca4-4a59-9824-23e9ce4093bf
		summarizeBy: none
		sourceColumn: id_fuente

		annotation SummarizationSetBy = Automatic

	column Fuente
		dataType: string
		lineageTag: d5051439-8cf1-4e6e-8350-3c0252e58e35
		summarizeBy: none
		sourceColumn: Fuente

		annotation SummarizationSetBy = Automatic

	partition Fuente = m
		mode: import
		queryGroup: Dimensiones
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\evasquez\OneDrive - Bolsa de Cereales de Buenos Aires\Documentos - Instituto Estudios Económicos\Dashboards\Monitor Economico\Outputs\Tablas_Dimensiones.xlsx"), null, true),
				    Fuente_Sheet = Origen{[Item="Fuente",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Fuente_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id_fuente", Int64.Type}, {"Fuente", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

