table Medidas_Maíz
	lineageTag: 3847973f-7033-4317-8037-e8315d92b04a

	measure 'En Circuito Comercial (Mtn)' = ```
			
			[Existencias Actuales (Mtn)_Circuito]
			- [Stock Inicial Maíz por Campaña (Mtn)_Circuito] 
			+ [Molienda_Acumulada (Mtn)_Circuito]
			+ [Exportaciones_Acumuladas (MTn)_Circuito]
			```
		lineageTag: 7b506d10-d1d9-4a97-9207-88dfeb291b9b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% En Flujo Comercial' = ```
			
			DIVIDE(
			    [En Circuito Comercial (Mtn)],
			    [Producción (Mtn)],
			    BLANK()
			)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: e6e90e09-b0ce-4fda-a3fc-e6ded2bca729

	measure 'Stock Inicial Maíz por Campaña (Mtn)_Circuito' =
			
			CALCULATE(
			    SUM(Tabla_Stock_Cultivos[Stock Inicial (Mtn)]),
			    Tabla_Stock_Cultivos[Producto] = "Maíz"
			)
		lineageTag: 888654ea-44d5-4560-82c4-d76ba25e0307

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Molienda Acumulada Maíz (Mtn)' = ```
			
			VAR OrdenLimite =
			    CALCULATE(
			        MAX('Balances'[Orden Comercial]),
			        FILTER(
			            ALL('Balances'),
			            RELATED('Campaña'[id_campaña]) = 15 &&
			            'Balances'[Producto] = "Maíz Seca y Humeda" &&
			            'Balances'[Atributo] = "Molienda" &&
			            'Balances'[Fuente] = "Min Agro" &&
			            'Balances'[Referencia] = "Seca y Húmeda" &&
			            NOT ISBLANK('Balances'[Valor]) &&
			            NOT ISBLANK('Balances'[Orden Comercial])
			        )
			    )
			
			RETURN
			CALCULATE(
			    SUM('Balances'[Valor]) / 1000000,
			    FILTER(
			        ALL('Balances'),
			        RELATED('Campaña'[id_campaña]) = 15 &&
			        'Balances'[Producto] = "Maíz Seca y Humeda" &&
			        'Balances'[Atributo] = "Molienda" &&
			        'Balances'[Fuente] = "Min Agro" &&
			        'Balances'[Referencia] = "Seca y Húmeda" &&
			        NOT ISBLANK('Balances'[Valor]) &&
			        NOT ISBLANK('Balances'[Orden Comercial]) &&
			        'Balances'[Orden Comercial] <= OrdenLimite
			    )
			)
			
			
			```
		lineageTag: a4a8756c-bd46-44dd-aaf7-9d92d4705d55

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Exportaciones acumuladas Maíz (Mtn)' = ```
			
			VAR OrdenLimite =
			    CALCULATE(
			        MAX('Balances'[Orden Comercial]),
			        FILTER(
			            ALL('Balances'),
			            RELATED('Campaña'[id_campaña]) = 14 &&
			            'Balances'[Producto] = "Maíz" &&
			            'Balances'[Atributo] = "Exportaciones" &&
			            'Balances'[Fuente] = "Indec" &&
			            'Balances'[Referencia] = "total" &&
			            NOT ISBLANK('Balances'[Valor]) &&
			            NOT ISBLANK('Balances'[Orden Comercial])
			        )
			    )
			
			RETURN
			CALCULATE(
			    SUM('Balances'[Valor]) / 1000000,
			    FILTER(
			        ALL('Balances'),
			        RELATED('Campaña'[id_campaña]) = 14 &&
			        'Balances'[Producto] = "Maíz" &&
			        'Balances'[Atributo] = "Exportaciones" &&
			        'Balances'[Fuente] = "Indec" &&
			        'Balances'[Referencia] = "total" &&
			        NOT ISBLANK('Balances'[Valor]) &&
			        NOT ISBLANK('Balances'[Orden Comercial]) &&
			        'Balances'[Orden Comercial] <= OrdenLimite
			    )
			)
			
			```
		lineageTag: 7133b987-57de-4fcf-af94-45611cda0126

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Producción Est 23/24(Mtn)' = ```
			
			VAR CampanaFiltrada =
			    CALCULATE(
			        MAX('Campaña'[Campaña]),
			        'Campaña'[id_campaña] = 14
			    )
			
			VAR ValorCalculado =
			    CALCULATE(
			        SUM(Balances_Cultivos[Valor]),
			        Balances_Cultivos[att] = "prd",
			        Balances_Cultivos[Campaña] = CampanaFiltrada
			    )
			
			RETURN
			DIVIDE(ValorCalculado, 1000000)
			
			```
		formatString: 0.00
		lineageTag: 3ee1333d-2e02-447b-8372-e89c152040e5

	measure 'Exportación Est 23/24(Mtn)' = ```
			
			VAR CampanaFiltrada =
			    CALCULATE(
			        MAX('Campaña'[Campaña]),
			        'Campaña'[id_campaña] = 14
			    )
			
			VAR ValorCalculado =
			    CALCULATE(
			        SUM(Balances_Cultivos[Valor]),
			        Balances_Cultivos[att] = "exp",
			        Balances_Cultivos[Campaña] = CampanaFiltrada
			    )
			
			RETURN
			DIVIDE(ValorCalculado, 1000000)
			
			```
		lineageTag: 65e5f9ba-f180-41db-94c0-c71be469b1e6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Mínimo_Maíz =
			
			
			VAR CircuitoActual =
			    CALCULATE(
			        [Existencias Actuales (Mtn)_Circuito]
			        - [Stock Inicial Maíz por Campaña (Mtn)_Circuito]
			        + [Molienda_Acumulada (Mtn)_Circuito]
			        + [Exportaciones_Acumuladas (MTn)_Circuito],
			        'Campaña'[id_campaña] = 14
			    )
			
			VAR MaxCircuitoSobreProduccion =
			    CALCULATE(
			        MAXX(
			            VALUES('Campaña'[id_campaña]),
			            DIVIDE(
			                [Existencias Actuales (Mtn)_Circuito]
			                - [Stock Inicial Maíz por Campaña (Mtn)_Circuito]
			                + [Molienda_Acumulada (Mtn)_Circuito]
			                + [Exportaciones_Acumuladas (MTn)_Circuito],
			                [Producción (Mtn)],
			                BLANK()
			            )
			        ),
			        'Campaña'[id_campaña] >= 10 && 'Campaña'[id_campaña] <= 13
			    )
			
			RETURN
			DIVIDE(CircuitoActual, MaxCircuitoSobreProduccion, BLANK())
		lineageTag: d9ebc6c1-f7e8-44f9-893f-d8be09cc1750

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Máximo_Maíz = ```
			
			VAR CircuitoActual =
			    CALCULATE(
			        [Existencias Actuales (Mtn)_Circuito]
			        - [Stock Inicial Maíz por Campaña (Mtn)_Circuito]
			        + [Molienda_Acumulada (Mtn)_Circuito]
			        + [Exportaciones_Acumuladas (MTn)_Circuito],
			        'Campaña'[id_campaña] = 14
			    )
			
			VAR MinCircuitoSobreProduccion =
			    CALCULATE(
			        MINX(
			            VALUES('Campaña'[id_campaña]),
			            DIVIDE(
			                [Existencias Actuales (Mtn)_Circuito]
			                - [Stock Inicial Maíz por Campaña (Mtn)_Circuito]
			                + [Molienda_Acumulada (Mtn)_Circuito]
			                + [Exportaciones_Acumuladas (MTn)_Circuito],
			                [Producción (Mtn)],
			                BLANK()
			            )
			        ),
			        'Campaña'[id_campaña] >= 10 && 'Campaña'[id_campaña] <= 13
			    )
			
			RETURN
			DIVIDE(CircuitoActual, MinCircuitoSobreProduccion, BLANK())
			
			```
		lineageTag: 0e9cbcf3-1008-4dbd-9918-73301e55a370

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Promedio_Maíz = ```
			
			VAR CircuitoActual =
			    CALCULATE(
			        [Existencias Actuales (Mtn)_Circuito]
			        - [Stock Inicial Maíz por Campaña (Mtn)_Circuito]
			        + [Molienda_Acumulada (Mtn)_Circuito]
			        + [Exportaciones_Acumuladas (MTn)_Circuito],
			        'Campaña'[id_campaña] = 14
			    )
			
			VAR PromedioCircuitoSobreProduccion =
			    CALCULATE(
			        AVERAGEX(
			            VALUES('Campaña'[id_campaña]),
			            DIVIDE(
			                [Existencias Actuales (Mtn)_Circuito]
			                - [Stock Inicial Maíz por Campaña (Mtn)_Circuito]
			                + [Molienda_Acumulada (Mtn)_Circuito]
			                + [Exportaciones_Acumuladas (MTn)_Circuito],
			                [Producción (Mtn)],
			                BLANK()
			            )
			        ),
			        'Campaña'[id_campaña] >= 10 && 'Campaña'[id_campaña] <= 13
			    )
			
			RETURN
			DIVIDE(CircuitoActual, PromedioCircuitoSobreProduccion, BLANK())
			
			```
		lineageTag: 4110691b-b0e2-4658-b650-0d0385a4f66f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Existencias Actuales (Mtn)_Circuito' =
			
			SUM(Existencias_Maiz_Historico[Mtn])
		lineageTag: 2963cac2-2633-431b-a30b-3433db910754

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Exportaciones_Acumuladas (MTn)_Circuito' =
			
			VAR OrdenLimite =
			    CALCULATE(
			        MAX('Balances'[Orden Comercial]),
			        FILTER(
			            ALL('Balances'),
			            RELATED('Campaña'[id_campaña]) = 14 &&
			            'Balances'[Producto] = "Maíz" &&
			            'Balances'[Atributo] = "Exportaciones" &&
			            'Balances'[Fuente] = "Indec" &&
			            'Balances'[Referencia] = "total" &&
			            NOT ISBLANK('Balances'[Valor])
			        )
			    )
			
			VAR CampanaActual = SELECTEDVALUE('Campaña'[id_campaña])
			
			RETURN
			CALCULATE(
			    SUM('Balances'[Valor]) / 1000000,
			    FILTER(
			        ALL('Balances'),
			        RELATED('Campaña'[id_campaña]) = CampanaActual &&
			        'Balances'[Producto] = "Maíz" &&
			        'Balances'[Atributo] = "Exportaciones" &&
			        'Balances'[Fuente] = "Indec" &&
			        'Balances'[Referencia] = "total" &&
			        NOT ISBLANK('Balances'[Valor]) &&
			        'Balances'[Orden Comercial] <= OrdenLimite
			    )
			)
		lineageTag: 31681a7b-6ef8-4bfa-871a-a8ac11e6b25a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Molienda_Acumulada (Mtn)_Circuito' = ```
			
			VAR OrdenLimite =
			    CALCULATE(
			        MAX('Balances'[Orden Comercial]),
			        FILTER(
			            ALL('Balances'),
			            RELATED('Campaña'[id_campaña]) = 14 &&
			            'Balances'[Producto] = "Maíz Seca y Humeda" &&
			            'Balances'[Atributo] = "Molienda" &&
			            'Balances'[Fuente] = "Min Agro" &&
			            'Balances'[Referencia] = "Seca y Húmeda" &&
			            NOT ISBLANK('Balances'[Valor]) &&
			            NOT ISBLANK('Balances'[Orden Comercial])
			        )
			    )
			
			VAR CampanaActual = SELECTEDVALUE('Campaña'[id_campaña])
			
			RETURN
			CALCULATE(
			    SUM('Balances'[Valor]) / 1000000,
			    FILTER(
			        ALL('Balances'),
			        RELATED('Campaña'[id_campaña]) = CampanaActual &&
			        'Balances'[Producto] = "Maíz Seca y Humeda" &&
			        'Balances'[Atributo] = "Molienda" &&
			        'Balances'[Fuente] = "Min Agro" &&
			        'Balances'[Referencia] = "Seca y Húmeda" &&
			        NOT ISBLANK('Balances'[Valor]) &&
			        NOT ISBLANK('Balances'[Orden Comercial]) &&
			        'Balances'[Orden Comercial] <= OrdenLimite
			    )
			)
			
			```
		lineageTag: f21ae311-983e-4232-a188-3bc8a053e066

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'vs 2023/24' = ```
			
			VAR UltimoMesCampana14 =
			    CALCULATE(
			        MAX('Balances'[Orden Comercial]),
			        FILTER(
			            'Balances',
			            'Balances'[Campaña] = "2024/25" &&
			            'Balances'[Meses] <> "Total" &&
			            NOT(ISBLANK('Balances'[Valor]))
			        )
			    )
			
			VAR AcumuladoCampana14 =
			    CALCULATE(
			        SUM('Balances'[Valor]) / 1000000,
			        'Balances'[Campaña] = "2024/25",
			        'Balances'[Meses] <> "Total",
			        'Balances'[Orden Comercial] <= UltimoMesCampana14
			    )
			
			VAR AcumuladoCampana13 =
			    CALCULATE(
			        SUM('Balances'[Valor]) / 1000000,
			        'Balances'[Campaña] = "2023/24",
			        'Balances'[Meses] <> "Total",
			        'Balances'[Orden Comercial] <= UltimoMesCampana14
			    )
			
			VAR Diferencia_Porcentaje = 
			    DIVIDE(
			        AcumuladoCampana14 - AcumuladoCampana13,
			        AcumuladoCampana13,
			        0
			    )
			
			RETURN
			Diferencia_Porcentaje
			```
		lineageTag: dba644c9-6a18-47f8-89cd-3d18eb474dc3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'vs PU5C' = ```
			
			VAR UltimoOrdenCampana14 =
			    CALCULATE(
			        MAX('Balances'[Orden Comercial]),
			        FILTER(
			            'Balances',
			            'Balances'[Campaña] = "2024/25" &&
			            NOT(ISBLANK('Balances'[Valor]))
			        )
			    )
			
			VAR AcumuladoCampana14 =
			    CALCULATE(
			        SUM('Balances'[Valor]),
			        'Balances'[Campaña] = "2024/25",
			        'Balances'[Orden Comercial] <= UltimoOrdenCampana14
			    )
			
			VAR AcumuladoCampana16 =
			    CALCULATE(
			        SUM('Balances'[Valor]),
			        'Balances'[Campaña] = "PU5C",
			        'Balances'[Orden Comercial] <= UltimoOrdenCampana14
			    )
			
			VAR Diferencia_Porcentaje = 
			    DIVIDE(
			        AcumuladoCampana14 - AcumuladoCampana16,
			        AcumuladoCampana16,
			        0
			    )
			
			RETURN
			Diferencia_Porcentaje
			```
		lineageTag: 5599642e-804c-4e82-bb36-29e4b995edcf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'vs I.C y vs PU5C' = ```
			
			    FORMAT([vs 2023/24],"0%")
			    &  
			    "   |   "  
			    &
			    FORMAT([vs PU5C], "0%")
			```
		lineageTag: aa2b5856-168f-474c-90f9-e51faf2c5def

	partition Medidas_Maíz = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

