table Producto
	lineageTag: 6babf4ed-9f9e-46ac-960e-fcf6d4f4e23b

	column id_producto
		dataType: int64
		formatString: 0
		lineageTag: 3edb6a16-5944-4de6-a98a-322f4b057644
		summarizeBy: sum
		sourceColumn: id_producto

		annotation SummarizationSetBy = Automatic

	column 'Producto '
		dataType: string
		lineageTag: faf0fb4f-ef3d-4750-8885-8a3eeb080fb4
		summarizeBy: none
		sourceColumn: "Producto "

		annotation SummarizationSetBy = Automatic

	partition Producto = m
		mode: import
		queryGroup: Dimensiones
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\evasquez\OneDrive - Bolsa de Cereales de Buenos Aires\Documentos - Instituto Estudios Económicos\Dashboards\Monitor Economico\Outputs\Tablas_Dimensiones.xlsx"), null, true),
				    Producto_Sheet = Origen{[Item="Producto",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Producto_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id_producto", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

